# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 IAMVanilka

"""These tests are generated by AI."""

from configparser import ConfigParser as RealConfigParser
from unittest.mock import Mock, MagicMock, mock_open
from pathlib import Path
import requests
import pytest
import shutil
import os

from modules.main import DLCTool
from modules.games.stellaris.stellaris_strategy import StellarisStrategy

@pytest.fixture
def strategy(tmp_path):
    return StellarisStrategy(game_dir=str(tmp_path))

@pytest.fixture
def fetcher(strategy):
    return DLCTool(strategy)

class TestGetDlcsList:
    def test_success_case(self, strategy, mocker, tmp_path):
        """Тест: успешный ответ от API"""

        mock_response = Mock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            "data": {
                f"{strategy.app_id}": {
                    "extended": {
                        "listofdlc": "12345,67890,11223"
                    },
                    "dlc": {
                        "12345": {"name": "DLC 1"},
                        "67890": {"name": "DLC 2"},
                        "11223": {"name": "DLC 3"}
                    }
                }
            }
        }
        mocker.patch("pathlib.Path.home", return_value=tmp_path)
        mocker.patch("requests.get", return_value=mock_response)
        
        result = strategy.get_dlcs_list()
        
        assert result == {"12345": "DLC 1", "67890": "DLC 2", "11223": "DLC 3"}
        requests.get.assert_called_once_with(
            f"https://api.steamcmd.net/v1/info/{strategy.app_id}", 
            timeout=15
        )
    
    def test_connection_error(self, strategy, mocker, capsys, tmp_path):
        """Тест: ошибка соединения (имитируем блокировку в РФ)"""

        mocker.patch("pathlib.Path.home", return_value=tmp_path)
        mocker.patch(
            "requests.get", 
            side_effect=requests.exceptions.ConnectionError
        )
        
        with pytest.raises(requests.exceptions.ConnectionError, match="api.steamcmd.net"):
            strategy.get_dlcs_list()
    
    def test_non_200_status(self, strategy, mocker, tmp_path):
        """Тест: API вернул ошибку (например, 404 или 500)"""

        mocker.patch("pathlib.Path.home", return_value=tmp_path)
        mock_response = Mock()
        mock_response.status_code = 404
        mock_response.raise_for_status.side_effect = requests.exceptions.HTTPError("404 Client Error")
        mocker.patch("requests.get", return_value=mock_response)
        
        with pytest.raises(requests.exceptions.HTTPError):
            strategy.get_dlcs_list()

class TestCheckGameDir:
    def test_game_dir_valid(self, strategy, mocker):
        """Тест: файл 'stellaris' найден — метод молча проходит"""

        mocker.patch("os.listdir", return_value=["stellaris", "dlcs", "sound"])
        result = strategy.check_game_dir()
        
        assert result is None
        assert not hasattr(strategy, '_input_called')
    
    def test_game_dir_invalid_user_says_yes(self, strategy, mocker, capsys):
        """Тест: файла нет, пользователь ответил 'Y' — продолжаем"""

        mocker.patch("os.listdir", return_value=["dlc", "sound", "stellaris.exe", "launcher.exe"])
        mocker.patch("builtins.input", return_value="yes")
        
        result = strategy.check_game_dir()
        
        assert result is None
        captured = capsys.readouterr()
        assert "Cannot find 'stellaris' binary file" in captured.out
    
    def test_game_dir_invalid_user_says_no(self, strategy, mocker, capsys):
        """Тест: файла нет, пользователь ответил 'N' — программа завершается"""

        mocker.patch("os.listdir", return_value=["dlc", "sound", "stellaris.exe", "launcher.exe"])
        mocker.patch("builtins.input", return_value="no")
        
        with pytest.raises(SystemExit):
            strategy.check_game_dir()
        
        captured = capsys.readouterr()
        assert "Cannot find 'stellaris' binary file" in captured.out
        assert "Stopping. Please restart" in captured.out

class TestDownloadGoldberSteamlib:
    def test_download_success(self, strategy, mocker, capsys):
        """Тест: файл успешно скачан и записан"""

        mock_response_release = MagicMock()
        mock_response_release.status_code = 200
        mock_response_release.json.return_value = {
            "assets": [
                {"name": "emu-linux-release.tar.bz2", "browser_download_url": "https://example.com/download.tar.bz2"}
            ]
        }
        mock_response_download = MagicMock()
        mock_response_download.status_code = 200
        mock_response_download.headers = {"content-length": "4"}
        mock_response_download.iter_content.return_value = [b"data"]
        mock_response_download.__enter__.return_value = mock_response_download
        mock_response_download.__exit__.return_value = False

        mocker.patch("requests.get", side_effect=[mock_response_release, mock_response_download])
        mocker.patch("pathlib.Path.mkdir")
        mocker.patch("shutil.unpack_archive")
        mocker.patch("shutil.move")
        mocker.patch("shutil.rmtree")
        mock_file = mock_open()
        mocker.patch("builtins.open", mock_file)
        
        result = strategy.download_library()
        assert result is None
        
        assert requests.get.call_count == 2
        assert requests.get.call_args_list[0] == ((strategy.lib_download_url,), {'timeout': 15})
        assert requests.get.call_args_list[1] == (("https://example.com/download.tar.bz2",), {'stream': True, 'timeout': 30})
        temp_dir = strategy.game_dir / 'temp'
        mock_file.assert_called_once_with(temp_dir / "emu-linux-release.tar.bz2", 'wb')
        mock_file().write.assert_called_once_with(b"data")
        
        captured = capsys.readouterr()
        assert "Downloading goldberg lib started..." in captured.out
        assert "Goldberg lib successfully installed!" in captured.out
    
    def test_download_failed_status(self, strategy, mocker):
        """Тест: сервер вернул ошибку (404, 500 и т.д.)"""

        mock_response = MagicMock()
        mock_response.status_code = 404
        mock_response.raise_for_status.side_effect = requests.exceptions.HTTPError("404 Client Error")
        mocker.patch("pathlib.Path.mkdir")
        mocker.patch("requests.get", return_value=mock_response)
        mock_file = mock_open()
        mocker.patch("builtins.open", mock_file)
        
        with pytest.raises(requests.exceptions.RequestException):
            strategy.download_library()
        mock_file.assert_not_called()
    
    def test_download_connection_error(self, strategy, mocker):
        """Тест: ошибка сети (таймаут, нет подключения)"""

        mocker.patch("pathlib.Path.mkdir")
        mocker.patch(
            "requests.get", 
            side_effect=requests.exceptions.ConnectionError
        )
        mock_file = mock_open()
        mocker.patch("builtins.open", mock_file)
        
        with pytest.raises(requests.exceptions.RequestException):
            strategy.download_library()
        mock_file.assert_not_called()

class TestCreateGoldbergConfigs:
    def test_create_success(self, strategy, mocker):
        """Тест: успешное создание конфигов"""

        mocker.patch("pathlib.Path.mkdir")
        mock_config = mocker.patch("configparser.ConfigParser")
        mock_config_instance = RealConfigParser()
        mock_config_instance.write = Mock()
        mock_config.return_value = mock_config_instance
        mock_open = mocker.patch("builtins.open")
        
        dlcs_list = {"100": "DLC100", "200": "DLC200", "300": "DLC300"}
        strategy.create_configs(dlcs_list)
        
        Path.mkdir.assert_called_once_with(exist_ok=True, parents=True)
        assert dict(mock_config_instance['app::dlcs']) == dlcs_list
        assert dict(mock_config_instance['app::cloud_save::general']) == {"create_default_dir": "1"}
        mock_config_instance.write.assert_called_once()
        assert mock_open.call_count == 2
        mock_open.assert_any_call(strategy.game_dir / "steam_settings/configs.app.ini", 'w')
        mock_open.assert_any_call(strategy.game_dir / "steam_settings/steam_appid.txt", 'w')

    def test_create_error(self, strategy, mocker):
        """Тест: ошибка при создании конфигов"""

        mocker.patch("pathlib.Path.mkdir", side_effect=Exception("Mkdir error"))
        
        with pytest.raises(Exception, match="Error creating goldberg configs"):
            strategy.create_configs({})

class TestDownloadDlcs:
    def test_download_parse_and_save(self, strategy, mocker, capsys):
        """Тест: парсинг HTML, скачивание ZIP-архивов и прогресс-бар"""

        # В новом коде download_dlcs просто скачивает файлы из списка
        # Нет парсинга HTML, это было в старом коде
        # Нужно адаптировать тест под новый метод

        data_to_download = ["dlc_pack_1", "dlc_pack_2"]
        
        mock_file_response = Mock()
        mock_file_response.status_code = 200
        mock_file_response.headers = {"content-length": "1024"}
        mock_file_response.iter_content.return_value = [b"x" * 512, b"y" * 512]
        mock_file_response.__enter__ = Mock(return_value=mock_file_response)
        mock_file_response.__exit__ = Mock(return_value=False)
        
        mocker.patch("requests.get", return_value=mock_file_response)
        mocker.patch("os.makedirs")
        mock_open_file = mock_open()
        mocker.patch("builtins.open", mock_open_file)

        strategy.download_dlcs(data_to_download)
        
        captured = capsys.readouterr()
        assert "DLCs downloaded successfully!" in captured.out

    def test_download_no_zip_files(self, strategy, mocker, capsys):
        """Тест: список файлов пустой"""

        strategy.download_dlcs([])
        
        captured = capsys.readouterr()
        assert "All DLCs is downloaded! Nothing to download." in captured.out

    def test_download_request_exception(self, strategy, mocker):
        """Тест: ошибка при скачивании файла (таймаут, обрыв связи)"""
        
        mocker.patch("requests.get", side_effect=requests.exceptions.RequestException("Network error"))
        mocker.patch("os.makedirs")
        
        with pytest.raises(requests.exceptions.RequestException):
            strategy.download_dlcs(["test"])

class TestUnzipFiles:
    def test_unpack_success(self, mocker, capsys, tmp_path):
        """Тест: успешная распаковка архивов и удаление исходных zip"""
        from modules.utils import unzip_files
        # Мокаем список файлов в директории
        dir_to_unzip = tmp_path / "dlc"
        dir_to_unzip.mkdir()
        mocker.patch(
            "os.listdir", 
            return_value=["dlc1.zip", "dlc2.zip", "readme.txt"]  # txt должен игнорироваться
        )
        mocker.patch("shutil.unpack_archive")
        mocker.patch("os.remove")
        
        unzip_files(dir_to_unzip)
        
        # unpack_archive должен вызваться 2 раза (только для zip)
        assert shutil.unpack_archive.call_count == 2
        # remove должен вызваться 2 раза (удаление исходных архивов)
        assert os.remove.call_count == 2
        
        captured = capsys.readouterr()
        assert "Files successfully unziped!" in captured.out

    def test_unpack_error(self, mocker, tmp_path):
        """Тест: ошибка при распаковке (битый архив)"""
        from modules.utils import unzip_files
        dir_to_unzip = tmp_path / "dlc"
        dir_to_unzip.mkdir()
        mocker.patch("os.listdir", return_value=["corrupted.zip"])
        mocker.patch(
            "shutil.unpack_archive", 
            side_effect=Exception("Bad archive")
        )
        
        with pytest.raises(Exception, match="Error during unpacking dlc archives!"):
            unzip_files(dir_to_unzip)

class TestInstallMethods:
    def test_install_libs_flow(self, fetcher, mocker, capsys):
        """Тест: полный сценарий установки библиотек"""
        mocker.patch.object(fetcher.strategy, "get_dlcs_list", return_value={})
        mocker.patch.object(fetcher.strategy, "download_library")
        mocker.patch.object(fetcher.strategy, "create_configs")
        
        fetcher.install_only_libs()
        
        fetcher.strategy.download_library.assert_called_once()
        fetcher.strategy.create_configs.assert_called_once_with({})

    def test_install_dlcs_flow(self, fetcher, mocker, capsys):
        """Тест: полный сценарий установки DLC"""
        mocker.patch("modules.main.files_hash_check", return_value=["dlc1", "dlc2"])
        mocker.patch.object(fetcher.strategy, "download_dlcs")
        mocker.patch("modules.main.unzip_files")
        
        fetcher.install_only_dlcs()
        
        fetcher.strategy.download_dlcs.assert_called_once_with(data_to_download=["dlc1", "dlc2"])
        # unzip_files.assert_called_once() but it's in utils, need to patch properly

    def test_full_install_flow_with_launch_yes(self, fetcher, mocker, capsys):
        """Тест: полная установка с запуском игры (пользователь ответил 'Yes')"""
        # Мокаем все внутренние шаги
        mocker.patch("modules.main.files_hash_check", return_value=[])
        mocker.patch.object(fetcher.strategy, "get_dlcs_list", return_value={})
        mocker.patch.object(fetcher.strategy, "download_library")
        mocker.patch.object(fetcher.strategy, "create_configs")
        mocker.patch.object(fetcher.strategy, "download_dlcs")
        mocker.patch("modules.main.unzip_files")
        mocker.patch("typer.confirm", return_value=True)

        
        fetcher.default_install_scenario()
        
        # Проверяем, что все шаги установки были вызваны
        fetcher.strategy.download_library.assert_called_once()
        fetcher.strategy.create_configs.assert_called_once_with({})
        fetcher.strategy.download_dlcs.assert_called_once_with([])
        # typer.confirm.assert_called_once_with("Installing done! Launch the game? (only for Steam)")
        # run_the_game.assert_called_once_with(fetcher.strategy.app_id)

    def test_full_install_flow_with_launch_no(self, fetcher, mocker):
        """Тест: полная установка без запуска игры (пользователь ответил 'No')"""
        mocker.patch("modules.utils.files_hash_check", return_value=[])
        mocker.patch.object(fetcher.strategy, "get_dlcs_list", return_value={})
        mocker.patch.object(fetcher.strategy, "download_library")
        mocker.patch.object(fetcher.strategy, "create_configs")
        mocker.patch.object(fetcher.strategy, "download_dlcs")
        mocker.patch("modules.utils.unzip_files")
        mocker.patch("typer.confirm", return_value=False)
        
        fetcher.default_install_scenario()

