"""These tests are generated by AI."""

import pytest
from unittest.mock import Mock, MagicMock, mock_open
from pathlib import Path
import requests
import os
import shutil
from modules.main import DLCTool, APP_ID

@pytest.fixture
def fetcher():
    return DLCTool(game_dir="/fake/game/path")

class TestGetDlcsList:
    def test_success_case(self, fetcher, mocker):
        """Тест: успешный ответ от API"""

        mock_response = Mock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            "data": {
                f"{APP_ID}": {
                    "extended": {
                        "listofdlc": "12345,67890,11223"
                    }
                }
            }
        }
        mocker.patch("requests.get", return_value=mock_response)
        
        result = fetcher._get_dlcs_list()
        
        assert result == ["12345", "67890", "11223"]
        requests.get.assert_called_once_with(
            f"https://api.steamcmd.net/v1/info/{APP_ID}", 
            timeout=15
        )
    
    def test_connection_error(self, fetcher, mocker, capsys):
        """Тест: ошибка соединения (имитируем блокировку в РФ)"""

        mocker.patch(
            "requests.get", 
            side_effect=requests.exceptions.ConnectionError
        )
        
        with pytest.raises(requests.exceptions.ConnectionError):
            fetcher._get_dlcs_list()

            captured = capsys.readouterr()
            assert "Error! Cannot reach https://api.steamcmd.net. Use VPN, if you from Russia." in captured.out   
    
    def test_non_200_status(self, fetcher, mocker, capsys):
        """Тест: API вернул ошибку (например, 404 или 500)"""

        mock_response = Mock()
        mock_response.status_code = 404
        mocker.patch("requests.get", return_value=mock_response)
        
        result = fetcher._get_dlcs_list()
        
        assert result is None
        captured = capsys.readouterr()
        assert "steamcmd.net returns 404 status code" in captured.out

class TestCheckGameDir:
    def test_game_dir_valid(self, fetcher, mocker):
        """Тест: файл 'stellaris' найден — метод молча проходит"""

        mocker.patch("os.listdir", return_value=["stellaris", "dlcs", "sound"])
        result = fetcher.check_game_dir()
        
        assert result is None
        assert not hasattr(fetcher, '_input_called')
    
    def test_game_dir_invalid_user_says_yes(self, fetcher, mocker, capsys):
        """Тест: файла нет, пользователь ответил 'Y' — продолжаем"""

        mocker.patch("os.listdir", return_value=["dlc", "sound", "stellaris.exe", "launcher.exe"])
        mocker.patch("builtins.input", return_value="yes")
        
        result = fetcher.check_game_dir()
        
        assert result is None
        captured = capsys.readouterr()
        assert "Cannot find 'stellaris' binary file" in captured.out
    
    def test_game_dir_invalid_user_says_no(self, fetcher, mocker, capsys):
        """Тест: файла нет, пользователь ответил 'N' — программа завершается"""

        mocker.patch("os.listdir", return_value=["dlc", "sound", "stellaris.exe", "launcher.exe"])
        mocker.patch("builtins.input", return_value="no")
        
        with pytest.raises(SystemExit):
            fetcher.check_game_dir()
        
        captured = capsys.readouterr()
        assert "Cannot find 'stellaris' binary file" in captured.out
        assert "Stopping. Please restart" in captured.out

class TestDownloadGoldberSteamlib:
    def test_download_success(self, fetcher, mocker, capsys):
        """Тест: файл успешно скачан и записан"""

        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.content = b"fake_library_binary_content"  # Имитируем бинарные данные
        mocker.patch("requests.get", return_value=mock_response)
        mock_file = mock_open()
        mocker.patch("builtins.open", mock_file)
        
        result = fetcher._download_goldberg_steamlib()
        assert result is None
        
        requests.get.assert_called_once_with(
            "https://gitlab.com/Mr_Goldberg/goldberg_emulator/-/jobs/4247811310/artifacts/raw/linux/x86_64/libsteam_api.so?inline=false",
            timeout=15
        )
        mock_file.assert_called_once_with(
            Path("/fake/game/path") / "libsteam_api.so", 
            "wb"  # write binary
        )
        mock_file().write.assert_called_once_with(b"fake_library_binary_content")
        
        captured = capsys.readouterr()
        assert "Downloading goldberg lib..." in captured.out
        assert "Goldberg lib successfully downloaded!" in captured.out
    
    def test_download_failed_status(self, fetcher, mocker, capsys):
        """Тест: сервер вернул ошибку (404, 500 и т.д.)"""

        mock_response = MagicMock()
        mock_response.status_code = 404
        mocker.patch("requests.get", return_value=mock_response)
        mock_file = mock_open()
        mocker.patch("builtins.open", mock_file)
        
        fetcher._download_goldberg_steamlib()
        mock_file.assert_not_called()
        captured = capsys.readouterr()
        assert "GitLab returns 404 status code" in captured.out
    
    def test_download_connection_error(self, fetcher, mocker, capsys):
        """Тест: ошибка сети (таймаут, нет подключения)"""

        mocker.patch(
            "requests.get", 
            side_effect=requests.exceptions.ConnectionError
        )
        mock_file = mock_open()
        mocker.patch("builtins.open", mock_file)
        
        with pytest.raises(requests.exceptions.ConnectionError):
            fetcher._download_goldberg_steamlib()
            captured = capsys.readouterr()
            assert "Error! Cannot connect to gitlab.com. Check your network connection." in captured.out
        
        mock_file.assert_not_called()

class TestCreateDlcsFile:
    def test_create_success(self, fetcher, mocker):
        """Тест: успешное создание директории и файла dlc.txt"""

        mocker.patch("os.mkdir")
        mocker.patch("builtins.open", mock_open())
        mock_get_list = mocker.patch.object(
            fetcher, 
            "_get_dlcs_list", 
            return_value=["100", "200", "300"]
        )
        
        fetcher._create_dlcs_file()
        
        os.mkdir.assert_called_once_with(fetcher.game_dir / "steam_settings")
        mock_get_list.assert_called_once()
        open.assert_called_once_with(
            fetcher.game_dir / "steam_settings/dlc.txt", 
            "+w"
        )
        handle = open()
        handle.write.assert_any_call("100\n")
        handle.write.assert_any_call("200\n")
        handle.write.assert_any_call("300\n")

    def test_create_dir_exists(self, fetcher, mocker):
        """Тест: директория уже существует (FileExistsError) — программа не падает"""

        mocker.patch("os.mkdir", side_effect=FileExistsError)
        mocker.patch("builtins.open", mock_open())
        mocker.patch.object(fetcher, "_get_dlcs_list", return_value=[])
        
        result = fetcher._create_dlcs_file()
        assert result is None

    def test_create_permission_error(self, fetcher, mocker, capsys):
        """Тест: нет прав на создание файлов (PermissionError)"""

        mocker.patch("os.mkdir", side_effect=PermissionError)
        
        fetcher._create_dlcs_file()
        
        captured = capsys.readouterr()
        assert "Error! Unable to create required folders" in captured.out

class TestGetDlcsUrl:
    def test_fetch_success(self, fetcher, mocker):
        """Тест: успешное получение конфигурации с GitHub"""

        mock_response = Mock()
        mock_response.status_code = 200
        expected_data = {"url": "main.server.com", "alturl": "backup.server.com"}
        mock_response.json.return_value = expected_data
        
        mocker.patch("requests.get", return_value=mock_response)
        
        result = fetcher._get_dlcs_url()
        
        assert result == expected_data
        requests.get.assert_called_once_with(fetcher.GITHUB_DATA_URL)

    def test_fetch_non_200(self, fetcher, mocker, capsys):
        """Тест: GitHub вернул ошибку (например, 404)"""

        mock_response = Mock()
        mock_response.status_code = 404
        mocker.patch("requests.get", return_value=mock_response)
        
        result = fetcher._get_dlcs_url()
        
        assert result is None
        captured = capsys.readouterr()
        assert "GitHub returns 404 status code" in captured.out

    def test_fetch_connection_error(self, fetcher, mocker):
        """Тест: ошибка сети при обращении к GitHub"""

        mocker.patch(
            "requests.get", 
            side_effect=requests.exceptions.ConnectionError
        )
        
        with pytest.raises(requests.exceptions.ConnectionError):
            fetcher._get_dlcs_url()

class TestDownloadDlcs:
    def test_download_parse_and_save(self, fetcher, mocker, capsys):
        """Тест: парсинг HTML, скачивание ZIP-архивов и прогресс-бар"""

        mocker.patch.object(
            fetcher, 
            "_get_dlcs_url", 
            return_value={"url": "test.server.com", "alturl": "alt.server.com"}
        )
        
        mock_list_response = Mock()
        mock_list_response.status_code = 200
        mock_list_response.text = '''
            <html>
                <a href="dlc_pack_1.zip">dlc_pack_1.zip</a>
                <a href="dlc_pack_2.zip">dlc_pack_2.zip</a>
            </html>
        '''
        
        mock_file_response = Mock()
        mock_file_response.status_code = 200
        mock_file_response.headers = {"content-length": "1024"}
        mock_file_response.iter_content.return_value = [b"x" * 512, b"y" * 512]
        mock_file_response.__enter__ = Mock(return_value=mock_file_response)
        mock_file_response.__exit__ = Mock(return_value=False)
        
        mocker.patch(
            "requests.get", 
            side_effect=[mock_list_response, mock_file_response, mock_file_response]
        )
        
        mocker.patch("os.makedirs")
        mock_open_file = mock_open()
        mocker.patch("builtins.open", mock_open_file)

        mock_tqdm = mocker.patch("ldu_tool.tqdm")
        mock_tqdm_instance = Mock()
        mock_tqdm_instance.__enter__ = Mock(return_value=Mock())
        mock_tqdm_instance.__exit__ = Mock(return_value=False)
        mock_tqdm.return_value = mock_tqdm_instance

        fetcher._download_dlcs()
        
        assert mock_tqdm.call_count >= 2
        
        first_call_kwargs = mock_tqdm.call_args_list[0][1]
        assert "unit" in first_call_kwargs
        assert first_call_kwargs["unit"] == "B"

    def test_download_no_zip_files(self, fetcher, mocker, capsys):
        """Тест: на сервере нет .zip файлов (парсинг вернул пустой список)"""
        mocker.patch.object(fetcher, "_get_dlcs_url", return_value={"url": "s.com", "alturl": "a.com"})
        
        mock_response = Mock()
        mock_response.status_code = 200
        mock_response.text = "<html><body>No files here</body></html>"  # Нет ссылок на zip
        mocker.patch("requests.get", return_value=mock_response)
        mocker.patch("os.makedirs")
        
        fetcher._download_dlcs()
        
        captured = capsys.readouterr()
        assert "Error! Cannot find '.zip' files in the server" in captured.out

    def test_download_request_exception(self, fetcher, mocker):
        """Тест: ошибка при скачивании файла (таймаут, обрыв связи)"""
        mocker.patch.object(fetcher, "_get_dlcs_url", return_value={"url": "s.com", "alturl": "a.com"})
        
        # Первый запрос (список) успешный, второй (файл) падает
        mock_list = Mock(status_code=200, text='<a href="file.zip">file.zip</a>')
        mocker.patch(
            "requests.get", 
            side_effect=[mock_list, requests.exceptions.RequestException("Network error")]
        )
        mocker.patch("os.makedirs")
        
        with pytest.raises(requests.exceptions.RequestException):
            fetcher._download_dlcs()

class TestUnzipFiles:
    def test_unpack_success(self, fetcher, mocker, capsys):
        """Тест: успешная распаковка архивов и удаление исходных zip"""
        # Мокаем список файлов в директории
        mocker.patch(
            "os.listdir", 
            return_value=["dlc1.zip", "dlc2.zip", "readme.txt"]  # txt должен игнорироваться
        )
        mocker.patch("shutil.unpack_archive")
        mocker.patch("os.remove")
        
        fetcher._unzip_files()
        
        # unpack_archive должен вызваться 2 раза (только для zip)
        assert shutil.unpack_archive.call_count == 2
        # remove должен вызваться 2 раза (удаление исходных архивов)
        assert os.remove.call_count == 2
        
        captured = capsys.readouterr()
        assert "Files successfully unziped!" in captured.out

    def test_unpack_error(self, fetcher, mocker):
        """Тест: ошибка при распаковке (битый архив)"""
        mocker.patch("os.listdir", return_value=["corrupted.zip"])
        mocker.patch(
            "shutil.unpack_archive", 
            side_effect=Exception("Bad archive")
        )
        
        with pytest.raises(Exception, match="Error during unpacking dlc archives!"):
            fetcher._unzip_files()

class TestInstallMethods:
    def test_install_libs_flow(self, fetcher, mocker, capsys):
        """Тест: полный сценарий установки библиотек"""
        mocker.patch.object(fetcher, "_download_goldberg_steamlib")
        mocker.patch.object(fetcher, "_create_dlcs_file")
        
        fetcher.install_libs()
        
        fetcher._download_goldberg_steamlib.assert_called_once()
        fetcher._create_dlcs_file.assert_called_once()
        captured = capsys.readouterr()
        assert "Libs installing started" in captured.out
        assert "Libs installing done" in captured.out

    def test_install_dlcs_flow(self, fetcher, mocker, capsys):
        """Тест: полный сценарий установки DLC"""
        mocker.patch.object(fetcher, "_download_dlcs")
        
        fetcher.install_dlcs()
        
        fetcher._download_dlcs.assert_called_once()
        captured = capsys.readouterr()
        assert "DLCs installing started" in captured.out

    def test_full_install_flow_with_launch_yes(self, fetcher, mocker, capsys):
        """Тест: полная установка с запуском игры (пользователь ответил 'Yes')"""
        # Мокаем все внутренние шаги
        mocker.patch.object(fetcher, "_download_goldberg_steamlib")
        mocker.patch.object(fetcher, "_create_dlcs_file")
        mocker.patch.object(fetcher, "_download_dlcs")
        mocker.patch.object(fetcher, "_unzip_files")
        # Мокаем input и subprocess
        mocker.patch("builtins.input", return_value="yes")
        mock_subprocess = mocker.patch("subprocess.run")
        
        fetcher.install()
        
        # Проверяем, что все шаги установки были вызваны
        fetcher._download_goldberg_steamlib.assert_called_once()
        fetcher._unzip_files.assert_called_once()
        # Проверяем запуск Steam
        mock_subprocess.assert_called_once_with(
            ["bash", "-c", f"steam steam://run/{APP_ID}"]
        )

    def test_full_install_flow_with_launch_no(self, fetcher, mocker):
        """Тест: полная установка без запуска игры (пользователь ответил 'No')"""
        mocker.patch.object(fetcher, "_download_goldberg_steamlib")
        mocker.patch.object(fetcher, "_create_dlcs_file")
        mocker.patch.object(fetcher, "_download_dlcs")
        mocker.patch.object(fetcher, "_unzip_files")
        mocker.patch("builtins.input", return_value="no")
        mock_subprocess = mocker.patch("subprocess.run")
        
        fetcher.install()
        
        # Subprocess не должен вызываться, так как пользователь отказался
        mock_subprocess.assert_not_called()

    def test_full_install_invalid_input_retry(self, fetcher, mocker):
        """Тест: обработка неверного ввода при вопросе о запуске (цикл повторного ввода)"""
        mocker.patch.object(fetcher, "_download_goldberg_steamlib")
        mocker.patch.object(fetcher, "_create_dlcs_file")
        mocker.patch.object(fetcher, "_download_dlcs")
        mocker.patch.object(fetcher, "_unzip_files")
        # Сначала 'invalid', потом 'n'
        mocker.patch("builtins.input", side_effect=["invalid", "n"])
        mock_subprocess = mocker.patch("subprocess.run")
        
        fetcher.install()
        
        # Input должен вызваться 2 раза: первый раз с ошибкой, второй раз с валидным ответом
        assert input.call_count == 2
        mock_subprocess.assert_not_called()