# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 IAMVanilka

"""These tests are generated by AI."""

from configparser import ConfigParser as RealConfigParser
from unittest.mock import Mock, MagicMock, mock_open
from pathlib import Path
import requests
import pytest
import shutil
import os

from modules.main import DLCTool, APP_ID

@pytest.fixture
def fetcher():
    return DLCTool(game_dir="/fake/game/path")

class TestGetDlcsList:
    def test_success_case(self, fetcher, mocker, tmp_path):
        """Тест: успешный ответ от API"""

        mock_response = Mock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            "data": {
                f"{APP_ID}": {
                    "extended": {
                        "listofdlc": "12345,67890,11223"
                    },
                    "dlc": {
                        "12345": {"name": "DLC 1"},
                        "67890": {"name": "DLC 2"},
                        "11223": {"name": "DLC 3"}
                    }
                }
            }
        }
        mocker.patch("modules.main.Path.home", return_value=tmp_path)
        mocker.patch("requests.get", return_value=mock_response)
        
        result = fetcher._get_dlcs_list()
        
        assert result == {"12345": "DLC 1", "67890": "DLC 2", "11223": "DLC 3"}
        requests.get.assert_called_once_with(
            f"https://api.steamcmd.net/v1/info/{APP_ID}", 
            timeout=15
        )
    
    def test_connection_error(self, fetcher, mocker, capsys, tmp_path):
        """Тест: ошибка соединения (имитируем блокировку в РФ)"""

        mocker.patch("modules.main.Path.home", return_value=tmp_path)
        mocker.patch(
            "requests.get", 
            side_effect=requests.exceptions.ConnectionError
        )
        
        with pytest.raises(requests.exceptions.ConnectionError, match="api.steamcmd.net"):
            fetcher._get_dlcs_list()
    
    def test_non_200_status(self, fetcher, mocker, tmp_path):
        """Тест: API вернул ошибку (например, 404 или 500)"""

        mocker.patch("modules.main.Path.home", return_value=tmp_path)
        mock_response = Mock()
        mock_response.status_code = 404
        mock_response.raise_for_status.side_effect = requests.exceptions.HTTPError("404 Client Error")
        mocker.patch("requests.get", return_value=mock_response)
        
        with pytest.raises(requests.exceptions.HTTPError):
            fetcher._get_dlcs_list()

class TestCheckGameDir:
    def test_game_dir_valid(self, fetcher, mocker):
        """Тест: файл 'stellaris' найден — метод молча проходит"""

        mocker.patch("os.listdir", return_value=["stellaris", "dlcs", "sound"])
        result = fetcher.check_game_dir()
        
        assert result is None
        assert not hasattr(fetcher, '_input_called')
    
    def test_game_dir_invalid_user_says_yes(self, fetcher, mocker, capsys):
        """Тест: файла нет, пользователь ответил 'Y' — продолжаем"""

        mocker.patch("os.listdir", return_value=["dlc", "sound", "stellaris.exe", "launcher.exe"])
        mocker.patch("builtins.input", return_value="yes")
        
        result = fetcher.check_game_dir()
        
        assert result is None
        captured = capsys.readouterr()
        assert "Cannot find 'stellaris' binary file" in captured.out
    
    def test_game_dir_invalid_user_says_no(self, fetcher, mocker, capsys):
        """Тест: файла нет, пользователь ответил 'N' — программа завершается"""

        mocker.patch("os.listdir", return_value=["dlc", "sound", "stellaris.exe", "launcher.exe"])
        mocker.patch("builtins.input", return_value="no")
        
        with pytest.raises(SystemExit):
            fetcher.check_game_dir()
        
        captured = capsys.readouterr()
        assert "Cannot find 'stellaris' binary file" in captured.out
        assert "Stopping. Please restart" in captured.out

class TestDownloadGoldberSteamlib:
    def test_download_success(self, fetcher, mocker, capsys):
        """Тест: файл успешно скачан и записан"""

        mock_response_release = MagicMock()
        mock_response_release.status_code = 200
        mock_response_release.json.return_value = {
            "assets": [
                {"name": fetcher.asset_name, "browser_download_url": "https://example.com/download.tar.bz2"}
            ]
        }
        mock_response_download = MagicMock()
        mock_response_download.status_code = 200
        mock_response_download.headers = {"content-length": "4"}
        mock_response_download.iter_content.return_value = [b"data"]
        mock_response_download.__enter__.return_value = mock_response_download
        mock_response_download.__exit__.return_value = False

        mocker.patch("requests.get", side_effect=[mock_response_release, mock_response_download])
        mocker.patch("pathlib.Path.mkdir")
        mocker.patch("shutil.unpack_archive")
        mocker.patch("shutil.move")
        mocker.patch("shutil.rmtree")
        mock_file = mock_open()
        mocker.patch("builtins.open", mock_file)
        
        result = fetcher._download_goldberg_steamlib()
        assert result is None
        
        assert requests.get.call_count == 2
        assert requests.get.call_args_list[0] == ((fetcher.github_gbe_url,), {'timeout': 15})
        assert requests.get.call_args_list[1] == (("https://example.com/download.tar.bz2",), {'stream': True, 'timeout': 60})
        temp_dir = fetcher.game_dir / 'temp'
        mock_file.assert_called_once_with(temp_dir / fetcher.asset_name, 'wb')
        mock_file().write.assert_called_once_with(b"data")
        
        captured = capsys.readouterr()
        assert "Downloading goldberg lib started..." in captured.out
        assert "Goldberg lib successfully installed!" in captured.out
    
    def test_download_failed_status(self, fetcher, mocker):
        """Тест: сервер вернул ошибку (404, 500 и т.д.)"""

        mock_response = MagicMock()
        mock_response.status_code = 404
        mock_response.raise_for_status.side_effect = requests.exceptions.HTTPError("404 Client Error")
        mocker.patch("pathlib.Path.mkdir")
        mocker.patch("requests.get", return_value=mock_response)
        mock_file = mock_open()
        mocker.patch("builtins.open", mock_file)
        
        with pytest.raises(requests.exceptions.RequestException):
            fetcher._download_goldberg_steamlib()
        mock_file.assert_not_called()
    
    def test_download_connection_error(self, fetcher, mocker):
        """Тест: ошибка сети (таймаут, нет подключения)"""

        mocker.patch("pathlib.Path.mkdir")
        mocker.patch(
            "requests.get", 
            side_effect=requests.exceptions.ConnectionError
        )
        mock_file = mock_open()
        mocker.patch("builtins.open", mock_file)
        
        with pytest.raises(requests.exceptions.RequestException):
            fetcher._download_goldberg_steamlib()
        mock_file.assert_not_called()

class TestCreateGoldbergConfigs:
    def test_create_success(self, fetcher, mocker):
        """Тест: успешное создание конфигов"""

        mocker.patch("pathlib.Path.mkdir")
        mock_get_list = mocker.patch.object(
            fetcher, 
            "_get_dlcs_list", 
            return_value={"100": "DLC100", "200": "DLC200", "300": "DLC300"}
        )
        mock_config = mocker.patch("configparser.ConfigParser")
        mock_config_instance = RealConfigParser()
        mock_config_instance.write = Mock()
        mock_config.return_value = mock_config_instance
        mock_open = mocker.patch("builtins.open")
        
        fetcher._create_goldberg_configs()
        
        Path.mkdir.assert_called_once_with(exist_ok=True, parents=True)
        mock_get_list.assert_called_once()
        assert dict(mock_config_instance['app::dlcs']) == {"100": "DLC100", "200": "DLC200", "300": "DLC300"}
        assert dict(mock_config_instance['app::cloud_save::general']) == {"create_default_dir": "1"}
        mock_config_instance.write.assert_called_once()
        assert mock_open.call_count == 2
        mock_open.assert_any_call(fetcher.game_dir / "steam_settings/configs.app.ini", 'w')
        mock_open.assert_any_call(fetcher.game_dir / "steam_settings/steam_appid.txt", 'w')

    def test_create_error(self, fetcher, mocker):
        """Тест: ошибка при создании конфигов"""

        mocker.patch("pathlib.Path.mkdir", side_effect=Exception("Mkdir error"))
        
        with pytest.raises(Exception, match="Error creating goldberg configs"):
            fetcher._create_goldberg_configs()

class TestGetDlcsUrl:
    def test_fetch_success(self, fetcher, mocker):
        """Тест: успешное получение конфигурации с GitHub"""

        mock_response = Mock()
        mock_response.status_code = 200
        expected_data = {"url": "main.server.com", "alturl": "backup.server.com"}
        mock_response.json.return_value = expected_data
        
        mocker.patch("requests.get", return_value=mock_response)
        
        result = fetcher._get_dlcs_url()
        
        assert result == expected_data
        assert requests.get.call_args_list[0] == ((fetcher.github_data_file_url,),)

    def test_fetch_non_200(self, fetcher, mocker, capsys):
        """Тест: GitHub вернул ошибку (например, 404)"""

        mock_response = Mock()
        mock_response.status_code = 404
        mocker.patch("requests.get", return_value=mock_response)
        
        result = fetcher._get_dlcs_url()
        
        assert result is None
        captured = capsys.readouterr()
        assert "GitHub returns 404 status code" in captured.out

    def test_fetch_connection_error(self, fetcher, mocker):
        """Тест: ошибка сети при обращении к GitHub"""

        mocker.patch(
            "requests.get", 
            side_effect=requests.exceptions.ConnectionError
        )
        
        with pytest.raises(requests.exceptions.ConnectionError):
            fetcher._get_dlcs_url()

class TestDownloadDlcs:
    def test_download_parse_and_save(self, fetcher, mocker, capsys):
        """Тест: парсинг HTML, скачивание ZIP-архивов и прогресс-бар"""

        mocker.patch.object(
            fetcher, 
            "_get_dlcs_url", 
            return_value={"url": "test.server.com", "alturl": "alt.server.com"}
        )
        
        mock_list_response = Mock()
        mock_list_response.status_code = 200
        mock_list_response.text = '''
            <html>
                <a href="dlc_pack_1.zip">dlc_pack_1.zip</a>
                <a href="dlc_pack_2.zip">dlc_pack_2.zip</a>
            </html>
        '''
        
        mock_file_response = Mock()
        mock_file_response.status_code = 200
        mock_file_response.headers = {"content-length": "1024"}
        mock_file_response.iter_content.return_value = [b"x" * 512, b"y" * 512]
        mock_file_response.__enter__ = Mock(return_value=mock_file_response)
        mock_file_response.__exit__ = Mock(return_value=False)
        
        mocker.patch(
            "requests.get", 
            side_effect=[mock_list_response, mock_file_response, mock_file_response]
        )
        
        mocker.patch("os.makedirs")
        mock_open_file = mock_open()
        mocker.patch("builtins.open", mock_open_file)

        mock_tqdm = mocker.patch("modules.main.tqdm")
        mock_tqdm_instance = Mock()
        mock_tqdm_instance.__enter__ = Mock(return_value=Mock())
        mock_tqdm_instance.__exit__ = Mock(return_value=False)
        mock_tqdm.return_value = mock_tqdm_instance

        fetcher._download_dlcs(force=True)
        
        assert mock_tqdm.call_count >= 2
        
        first_call_kwargs = mock_tqdm.call_args_list[0][1]
        assert "unit" in first_call_kwargs
        assert first_call_kwargs["unit"] == "B"

    def test_download_no_zip_files(self, fetcher, mocker, capsys):
        """Тест: на сервере нет .zip файлов (парсинг вернул пустой список)"""
        mocker.patch.object(fetcher, "_get_dlcs_url", return_value={"url": "s.com", "alturl": "a.com"})
        
        mock_response = Mock()
        mock_response.status_code = 200
        mock_response.text = "<html><body>No files here</body></html>"  # Нет ссылок на zip
        mocker.patch("requests.get", return_value=mock_response)
        mocker.patch("os.makedirs")
        
        fetcher._download_dlcs(force=True)
        
        captured = capsys.readouterr()
        assert "Error! Cannot find '.zip' files in the server" in captured.out

    def test_download_request_exception(self, fetcher, mocker):
        """Тест: ошибка при скачивании файла (таймаут, обрыв связи)"""
        mocker.patch.object(fetcher, "_get_dlcs_url", return_value={"url": "s.com", "alturl": "a.com"})
        
        # Первый запрос (список) успешный, второй (файл) падает
        mock_list = Mock(status_code=200, text='<a href="file.zip">file.zip</a>')
        mocker.patch(
            "requests.get", 
            side_effect=[mock_list, requests.exceptions.RequestException("Network error")]
        )
        mocker.patch("os.makedirs")
        
        with pytest.raises(requests.exceptions.RequestException):
            fetcher._download_dlcs(force=True)

class TestUnzipFiles:
    def test_unpack_success(self, fetcher, mocker, capsys):
        """Тест: успешная распаковка архивов и удаление исходных zip"""
        # Мокаем список файлов в директории
        mocker.patch(
            "os.listdir", 
            return_value=["dlc1.zip", "dlc2.zip", "readme.txt"]  # txt должен игнорироваться
        )
        mocker.patch("shutil.unpack_archive")
        mocker.patch("os.remove")
        
        fetcher._unzip_files()
        
        # unpack_archive должен вызваться 2 раза (только для zip)
        assert shutil.unpack_archive.call_count == 2
        # remove должен вызваться 2 раза (удаление исходных архивов)
        assert os.remove.call_count == 2
        
        captured = capsys.readouterr()
        assert "Files successfully unziped!" in captured.out

    def test_unpack_error(self, fetcher, mocker):
        """Тест: ошибка при распаковке (битый архив)"""
        mocker.patch("os.listdir", return_value=["corrupted.zip"])
        mocker.patch(
            "shutil.unpack_archive", 
            side_effect=Exception("Bad archive")
        )
        
        with pytest.raises(Exception, match="Error during unpacking dlc archives!"):
            fetcher._unzip_files()

class TestInstallMethods:
    def test_install_libs_flow(self, fetcher, mocker, capsys):
        """Тест: полный сценарий установки библиотек"""
        mocker.patch.object(fetcher, "_download_goldberg_steamlib")
        mocker.patch.object(fetcher, "_create_goldberg_configs")
        
        fetcher.install_libs()
        
        fetcher._download_goldberg_steamlib.assert_called_once()
        fetcher._create_goldberg_configs.assert_called_once()
        captured = capsys.readouterr()
        assert "Libs installing started" in captured.out
        assert "Libs installing done" in captured.out

    def test_install_dlcs_flow(self, fetcher, mocker, capsys):
        """Тест: полный сценарий установки DLC"""
        mocker.patch.object(fetcher, "hash_check", return_value=[])
        mocker.patch.object(fetcher, "_download_dlcs")
        mocker.patch.object(fetcher, "_unzip_files")
        
        fetcher.install_dlcs()
        
        fetcher._download_dlcs.assert_called_once()
        captured = capsys.readouterr()
        assert "DLCs installing started" in captured.out

    def test_full_install_flow_with_launch_yes(self, fetcher, mocker, capsys):
        """Тест: полная установка с запуском игры (пользователь ответил 'Yes')"""
        # Мокаем все внутренние шаги
        mocker.patch.object(fetcher, "_download_goldberg_steamlib")
        mocker.patch.object(fetcher, "_create_goldberg_configs")
        mocker.patch.object(fetcher, "_download_dlcs")
        mocker.patch.object(fetcher, "_unzip_files")
        mocker.patch("pathlib.Path.mkdir")
        mocker.patch("os.scandir", return_value=[])
        # Мокаем input и subprocess
        mocker.patch("builtins.input", return_value="yes")
        mock_subprocess = mocker.patch("subprocess.run")
        
        fetcher.install()
        
        # Проверяем, что все шаги установки были вызваны
        fetcher._download_goldberg_steamlib.assert_called_once()
        fetcher._unzip_files.assert_called_once()
        # Проверяем запуск Steam
        mock_subprocess.assert_called_once_with(
            ["bash", "-c", f"steam steam://run/{APP_ID} &"]
        )

    def test_full_install_flow_with_launch_no(self, fetcher, mocker):
        """Тест: полная установка без запуска игры (пользователь ответил 'No')"""
        mocker.patch.object(fetcher, "_download_goldberg_steamlib")
        mocker.patch.object(fetcher, "_create_goldberg_configs")
        mocker.patch.object(fetcher, "_download_dlcs")
        mocker.patch.object(fetcher, "_unzip_files")
        mocker.patch("pathlib.Path.mkdir")
        mocker.patch("os.scandir", return_value=[])
        mocker.patch("builtins.input", return_value="no")
        mock_subprocess = mocker.patch("subprocess.run")
        
        fetcher.install()
        
        mock_subprocess.assert_not_called()

    def test_full_install_invalid_input_retry(self, fetcher, mocker):
        """Тест: обработка неверного ввода при вопросе о запуске (цикл повторного ввода)"""
        mocker.patch.object(fetcher, "_download_goldberg_steamlib")
        mocker.patch.object(fetcher, "_create_goldberg_configs")
        mocker.patch.object(fetcher, "_download_dlcs")
        mocker.patch.object(fetcher, "_unzip_files")
        mocker.patch("pathlib.Path.mkdir")
        mocker.patch("os.scandir", return_value=[])
        # Сначала 'invalid', потом 'n'
        mocker.patch("builtins.input", side_effect=["invalid", "n"])
        mock_subprocess = mocker.patch("subprocess.run")
        
        fetcher.install()
        
        # Input должен вызваться 2 раза: первый раз с ошибкой, второй раз с валидным ответом
        assert input.call_count == 2
        mock_subprocess.assert_not_called()